### PR TITLE
http_client: Handle relative redirects

### LINKED ISSUE #6043: http_client fails to handle 301 with just a path properly
# Bug report

### What operating system and version are you using?
debian 

### What version of osquery are you using?
4.0.2_1

### What steps did you take to reproduce the issue?
* Run osquery on AWS where the EC2 instance has a role assigned to it which would allow pushes to firehose.
* Do not supply any credentials to osquery (it should attempt to use ec2 metadata to determine creds as final fall through)

### What did you expect to see?
attempts to push to firehose succeed

### What did you see instead?
Exception making HTTP request to URL (http://169.254.169.254/latest/meta-data/iam/security-credentials): Invalid URL

I built my own version of osquery to debug further and found that when osquery attempts to reach this url it receives a 301 redirect to "Location: /latest/meta-data/iam/security-credentials/".  It then passes this value as the url to URI which barfs as it doesnt match the expected URL format.

The follow_redirect logic needs to ensure the Location is translated into a proper URL.

### PR DESCRIPTION
**Pull request by theopolis**
This should fix #6043, where I think the root cause is the URI parsing. If there is no protocol/host/port then the URI is parsed incorrectly. We missed this due to the rarity of relative-redirects and due to the HTTP client being difficult to test.

This also adds a max of 10 redirects before the client gives up.

### CODE REVIEW

**Comment by theopolis** [comment]
```
osquery/remote/http_client.cpp:425:38: error: invalid operands to binary expression ('boost::optional<std::string>' (aka 'optional<basic_string<char, char_traits<char>, allocator<char> > >') and 'const char *')
          redir_url = req.protocol() + "://" + req.remoteHost() + redir_url;
                      ~~~~~~~~~~~~~~ ^ ~~~~~
/usr/include/c++/v1/iterator:761:1: note: candidate template ignored: could not match 'reverse_iterator<type-parameter-0-0>' against 'char const[4]'
operator+(typename reverse_iterator<_Iter>::difference_type __n, const reverse_iterator<_Iter>& __x)
^
```

File: osquery/remote/http_client.cpp [hunk 1]
```diff
@@ -412,23 +413,44 @@ Response Client::sendHTTPRequest(Request& req) {
...
+          if (req.remoteHost()) {
+            redir_url.insert(0, *req.remoteHost());
+          }
+          if (req.protocol()) {
+            redir_url.insert(0, "://");
+            redir_url.insert(0, *req.protocol());
+          }
+        } else {
+          // Absolute URI.
+          init_request = true;
```
Comment (zwass) [inline osquery/remote/http_client.cpp]: A possible optimization would be to check whether the protocol, host, and port match before setting this and initializing a new connection. Not necessary IMO for merging this PR.
