### PR TITLE
powershell/config: Add checks for character_frequencies

### LINKED ISSUE #5929: RAPIDJSON_ASSERT(IsArray()) is triggered
# Bug report
### What operating system and version are you using?
Windows 10 
version 1809
build 17763.805

### What version of osquery are you using?
4.02

### What steps did you take to reproduce the issue?
build and run a Debug osqueryd.exe in vs debugger

### What did you expect to see?
no asserts

### What did you see instead?
RAPIDJSON_ASSERT(IsArray())
from:
file: \osquery\tables\events\windows\powershell_events.cpp
function: PowershellEventSubscriber::addScriptResult
line 119   if (cf.Empty() || cf.Size() != kCharFreqVectorLen)
call stack  cf.Empty() -> RAPIDJSON_ASSERT(IsArray())

### PR DESCRIPTION
**Pull request by theopolis**
This fixes #5929.

I am not sure what this functionality provides and it is not tested. 

But this PR adds basic checks for the expectations for the format of the configuration JSON.

### CODE REVIEW

File: osquery/tables/events/windows/powershell_events.cpp [hunk 1]
```diff
@@ -106,25 +106,35 @@ void PowershellEventSubscriber::addScriptResult(Row& results) {
...
-  // Get the reassembled powershell scripts character frequency vector
-  std::vector<double> freqs(kCharFreqVectorLen, 0.0);
-  for (const auto chr : r["script_text"]) {
-    if (chr < kCharFreqVectorLen) {
-      freqs[chr] += 1.0 / r["script_text"].length();
-    }
+  const auto& doc = parser->getData().doc();
+  if (!doc.IsObject() || !doc.HasMember("feature_vectors") ||
+      !doc["feature_vectors"].HasMember("chracter_frequencies") ||
+      !doc["feature_vectors"]["chracter_frequencies"].IsArray()) {
```
Comment (Smjert) [inline osquery/tables/events/windows/powershell_events.cpp]: Typo
```suggestion
      !doc["feature_vectors"]["character_frequencies"].IsArray()) {
```

File: osquery/tables/events/windows/powershell_events.cpp [hunk 2]
```diff
@@ -106,25 +106,35 @@ void PowershellEventSubscriber::addScriptResult(Row& results) {
...
 
-  // Get the reassembled powershell scripts character frequency vector
-  std::vector<double> freqs(kCharFreqVectorLen, 0.0);
-  for (const auto chr : r["script_text"]) {
-    if (chr < kCharFreqVectorLen) {
-      freqs[chr] += 1.0 / r["script_text"].length();
-    }
+  const auto& doc = parser->getData().doc();
+  if (!doc.IsObject() || !doc.HasMember("feature_vectors") ||
+      !doc["feature_vectors"].HasMember("chracter_frequencies") ||
```
Comment (Smjert) [inline osquery/tables/events/windows/powershell_events.cpp]:
```suggestion
      !doc["feature_vectors"].HasMember("character_frequencies") ||
```

**Comment by packetzero** [comment]
yeah, we disabled this functionality in our fork.  The windows_events table will receive the same data (powershell script block logging).  As you can imagine, the script blocks can be rather large.  This does some cursory checking for obfuscation, if I remember correctly.
