### PR TITLE
Fix the reading of a certificate's serial

### LINKED ISSUE #5104: Certificate table shows serial number incorrectly.
# Bug report

The certificates table shows the serial number reversed (wrong endianess). This is because the serial number is actually a big int and it is encoded in little endian form. The code simply hex encodes the encoded form:

```
    std::string serial;
    boost::algorithm::hex(
        std::string(certContext->pCertInfo->SerialNumber.pbData,
                    certContext->pCertInfo->SerialNumber.pbData +
                        certContext->pCertInfo->SerialNumber.cbData),
        back_inserter(serial));
    r["serial"] = serial;
```

Which is incorrect since it needs to also deal with byte endianess. The overall result is that the serial number it shows is backwards from the one, say, windows certmgr shows.

image

### What operating system and version are you using?

Windows

### What version of osquery are you using?

3.2.4

### PR DESCRIPTION
**Pull request by mike-myers-tob**
This resolves #5104

The way I implemented this was to reverse the iterators that index the bytes, rather than reversing the resulting hexadecimal string. I believe this is a fast and correct way to do it, but let me know what you think.

### CODE REVIEW

File: osquery/tables/system/windows/certificates.cpp [hunk 1]
```diff
@@ -57,8 +57,17 @@ typedef struct _ENUM_ARG {
 } ENUM_ARG, *PENUM_ARG;
 
 template <typename Iterator>
-inline void toHexStr(Iterator begin, Iterator end, std::string& output) {
-  boost::algorithm::hex(std::string(begin, end), back_inserter(output));
+inline void toHexStr(Iterator begin,
```
Comment (theopolis) [inline osquery/tables/system/windows/certificates.cpp]: Is there an easy way to add a test for this behavior?

Comment (mike-myers-tob) [reply osquery/tables/system/windows/certificates.cpp]: My test was to use CertMgr (the UI) and manually compare the results, but for automating this:
- I suppose a test could query the cert store for a Microsoft root cert and check that the serial number is the expected one?
- Or it could insert a known test cert to the user cert store and read that back?

Comment (theopolis) [reply osquery/tables/system/windows/certificates.cpp]: Ah, I was more concerned with the correctness of `toHexStr`, testing the BE and LE modes.
