### PR TITLE
Fix SMC reading values

### LINKED ISSUE #5896: macOS: power_sensors table shows incorrect data
# Bug report

`power_sensors` table returns `-1.00` value for all power related SMC keys, instead of actual values.

```
osquery> .all power_sensors;
+------+----------+-------------------+-------+
| key  | category | name              | value |
+------+----------+-------------------+-------+
| PBLC | power    | Battery Rail      | -1.00 |
| PC0R | power    | Mainboard S0 Rail | -1.00 |
| PCPC | power    | CPU Cores         | -1.00 |
| PCPG | power    | CPU GFX           | -1.00 |
| PDTR | power    | DC In Total       | -1.00 |
| PG0R | power    | GPU Rail          | -1.00 |
| PSTR | power    | System Total      | -1.00 |
| IC0R | current  | CPU Rail          | -1.00 |
| ID0R | current  | Mainboard S0 Rail | -1.00 |
| IG0C | current  | GPU Rail          | -1.00 |
| IM0C | current  | Memory Controller | -1.00 |
| IPBR | current  | Charger BMON      | -1.00 |
| VD0R | voltage  | Mainboard S0 Rail | -1.00 |
| VG0C | voltage  | GPU Core          | -1.00 |
| VP0R | voltage  | 12V Rail          | -1.00 |
+------+----------+-------------------+-------+
```

Joining with `smc_keys` table, we can see that the raw SMC data is still there:

```
osquery> select power_sensors.key,
    ...> category,
    ...> name,
    ...> power_sensors.value as power_value,
    ...> smc_keys.value as raw_smc_value,
    ...> smc_keys.type as smc_type,
    ...> smc_keys.size as smc_size
    ...> FROM power_sensors
    ...> JOIN smc_keys where power_sensors.key = smc_keys.key;
+------+----------+-------------------+-------------+---------------+----------+----------+
| key  | category | name              | power_value | raw_smc_value | smc_type | smc_size |
+------+----------+-------------------+-------------+---------------+----------+----------+
| PBLC | power    | Battery Rail      | -1.00       | 00000000      | flt      | 4        |
| PC0R | power    | Mainboard S0 Rail | -1.00       | 1f3ea240      | flt      | 4        |
| PCPC | power    | CPU Cores         | -1.00       | 0107          | sp87     | 2        |
| PCPG | power    | CPU GFX           | -1.00       | 0000          | sp87     | 2        |
| PDTR | power    | DC In Total       | -1.00       | 00000000      | flt      | 4        |
| PG0R | power    | GPU Rail          | -1.00       | 94fb7040      | flt      | 4        |
| PSTR | power    | System Total      | -1.00       | 06f9          | sp87     | 2        |
| IC0R | current  | CPU Rail          | -1.00       | 91adc13e      | flt      | 4        |
| ID0R | current  | Mainboard S0 Rail | -1.00       | ff9fb939      | flt      | 4        |
| IG0C | current  | GPU Rail          | -1.00       | 00000000      | flt      | 4        |
| IM0C | current  | Memory Controller | -1.00       | 00000000      | flt      | 4        |
| IPBR | current  | Charger BMON      | -1.00       | 4d75983f      | flt      | 4        |
| VD0R | voltage  | Mainboard S0 Rail | -1.00       | 00000000      | flt      | 4        |
| VG0C | voltage  | GPU Core          | -1.00       | a5d54d3f      | flt      | 4        |
| VP0R | voltage  | 12V Rail          | -1.00       | 164c4641      | flt      | 4        |
+------+----------+-------------------+-------------+---------------+----------+----------+
```

This suggests that we may not be converting the various SMC data types correctly. I will dig deeper on this later.

### What operating system and version are you using?

```
osquery> SELECT version, build, platform FROM os_version;
 version = 10.13.6
   build = 17G8037
platform = darwin
```

This is seen on 10.13, 10.14 and 10.15

### What version of osquery are you using?

```
osquery> SELECT version from osquery_info;
version = 4.0.2-44-g6ba37014
```

### LINKED ISSUE #7627: `temperature_sensors` table misreports values on Apple Silicon
# Bug report

### What operating system and version are you using?

macOS 12.3.1 on an M1 Macbook Pro

### What version of osquery are you using?

osquery 5.2.3

### What steps did you take to reproduce the issue?

`osqueryi --line "select * from temperature_sensors order by fahrenheit desc;`

### What did you expect to see?

```
  key = TC0F
      name = CPU 1
   celsius = 69.3
fahrenheit = 156.7

       key = TCXC
      name = PECI CPU
   celsius = 69.0
fahrenheit = 156.2

       key = TC2C
      name = CPU Core 2
   celsius = 68.0
fahrenheit = 154.4
```

(etc)

### What did you see instead?

```
/usr/local/bin/osqueryi --line "select * from temperature_sensors order by fahrenheit desc;"
       key = TB0T
      name = Battery TS_MAX
   celsius = -1.0
fahrenheit = 30.2

       key = TB1T
      name = Battery 1
   celsius = -1.0
fahrenheit = 30.2

       key = TB2T
      name = Battery 2
   celsius = -1.0
fahrenheit = 30.2

       key = TG0H
      name = GPU Heatsink
   celsius = -1.0
fahrenheit = 30.2

       key = TW0P
      name = Airport Proximity
   celsius = -1.0
fahrenheit = 30.2

       key = Tp0C
      name = Power Supply 1 Alt.
   celsius = -1.0
fahrenheit = 30.2

       key = Ts0P
      name = Palm Rest
   celsius = -1.0
fahrenheit = 30.2
```

### PR DESCRIPTION
**Pull request by sgress454**
Fixes #7627
Fixes #5896
Fixes https://github.com/fleetdm/fleet/issues/26583

Fixes issues with SMC key readings used by the `temperature_sensors`, `power_sensors` and `fan_speed_sensors` tables.

SMC keys are already mysterious (there is no known definitive reference on the keys) and each new Apple product that comes out seems to have its own opinions about what data type keys should use.  At some point the temperature keys started using the `flt` and `ioft` types which we were not handling.  

Big shout out to @directionless for doing some digging on a previous ticket and leading me to https://github.com/dkorunic/iSMC which at least has a good listing of known types and clues as to how to convert them.  I've updated the code to handle `flt` and `ioft` as well all of the known `fp*`, `sp*`, `ui*` and `si*` types.  I also added tests for the conversions.  

Before:
image

After:
image

### CODE REVIEW

File: osquery/tables/system/darwin/smc_keys.cpp [hunk 1]
```diff
@@ -12,7 +12,10 @@
 
 #include <IOKit/IOKitLib.h>
 
+#include <osquery/logger/logger.h>
+
 #include <boost/algorithm/hex.hpp>
+#include <boost/algorithm/string.hpp>
```
Comment (sgress454) [inline osquery/tables/system/darwin/smc_keys.cpp:18]: for string trimming

File: osquery/tables/system/darwin/smc_keys.cpp [hunk 2]
```diff
@@ -379,28 +382,99 @@ inline uint32_t strtoul(const char *str, size_t size, size_t base) {
...
-float getConvertedValue(const std::string &smcType, const std::string &smcVal) {
-  // Convert hex string to decimal.
+inline uint64_t strtoull(const char* str, size_t size, size_t base) {
+  uint64_t total = 0;
+  for (size_t i = 0; i < size; i++) {
+    total += static_cast<uint64_t>(static_cast<unsigned char>(str[i]))
+             << (size - 1 - i) * 8;
+  }
+  return total;
+}
```
Comment (sgress454) [inline osquery/tables/system/darwin/smc_keys.cpp:392]: Companion to `strtoul`, but for 64 bit ints.

File: osquery/tables/system/darwin/smc_keys.cpp [hunk 3]
```diff
@@ -379,28 +382,99 @@ inline uint32_t strtoul(const char *str, size_t size, size_t base) {
...
+
+double getConvertedValue(const std::string& smcType,
```
Comment (sgress454) [inline osquery/tables/system/darwin/smc_keys.cpp:394]: Changed this (and all related vars) from `float` to `double` to handle 64-bit types.  We don't utilize any in tables right now, but there are definitely some 64-bit SMC keys (18 on my system) and this future-proofs us.

File: osquery/tables/system/darwin/smc_keys.cpp (hunk 2 above)
Comment (directionless) [reply osquery/tables/system/darwin/smc_keys.cpp:392]: Other parts of our code use `std::strtoull`. Should this?

File: osquery/tables/system/darwin/smc_keys.cpp [hunk 4]
```diff
@@ -379,28 +382,99 @@ inline uint32_t strtoul(const char *str, size_t size, size_t base) {
...
+      convertedVal =
+          static_cast<double>(static_cast<int16_t>(intVal)) / divisor;
+    } else {
+      convertedVal = static_cast<double>(intVal) / divisor;
+    }
+  }
+  // Big-endian 8/16/32/64 bit integers.
+  else if ((type[0] == 's' || type[0] == 'u') && type[1] == 'i') {
+    uint64_t intVal = strtoull(val.c_str(), size, 16);
+    if (type[0] == 's') {
```
Comment (directionless) [inline osquery/tables/system/darwin/smc_keys.cpp:462]: Why combine the `s` and `u` logic if it's just split apart on line 462?

**Review by directionless — COMMENTED** [review]
nice! A couple of small questions...

File: osquery/tables/system/darwin/smc_keys.cpp (hunk 2 above)
Comment (sgress454) [reply osquery/tables/system/darwin/smc_keys.cpp:392]: I don't think so.  The `std:strtoull` function does what you'd probably expect from the name: it takes a numeric string and interprets it as a number, e.g. the string `"12345"` becomes the unsigned long `12345`.  The `strtoul` function defined in smc_keys.cpp does something else entirely: it treats a string as a set of bytes representing an integer with big-endian encoding.  It's functionally the same as byte-swapping a string and `memcpy`ing the bytes into a new `uint32_t`.  I don't know why it was called `strtoul`, but for consistency I named the 64-bit version the same thing.  I'd be happy to rename them both, but without knowing the history I prefer to stay low-touch.

File: osquery/tables/system/darwin/smc_keys.cpp (hunk 4 above)
Comment (sgress454) [reply osquery/tables/system/darwin/smc_keys.cpp:462]: It's combining the `si` and `ui` logic, both of which start by interpreting the value as a big-endian int.  What we do with that int depends on whether it's `s`igned or `u`nsigned.

File: osquery/tables/system/darwin/smc_keys.cpp (hunk 2 above)
Comment (directionless) [reply osquery/tables/system/darwin/smc_keys.cpp:392]: I agreee consistency with the local function makes sense, though the divergence from `std::` seems unfortunate.

File: osquery/tables/system/darwin/smc_keys.cpp (hunk 4 above)
Comment (directionless) [reply osquery/tables/system/darwin/smc_keys.cpp:462]: Yeah.. I guess I'd duplicate the `strtoull` over the nested `if` But 🤷

**Review by directionless — APPROVED** [review]
