### PR TITLE
bug: Force shell to disable watchdog and logger

### LINKED ISSUE #6613: osqueryi can't quit with flag --disable_watchdog=false
### What operating system and version are you using?
CentOS Linux release 7.8.2003

### What version of osquery are you using?
4.4.0
### What steps did you take to reproduce the issue?
```bash
osqueryi --verbose --disable_watchdog=false

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0828 18:00:20.466588 26260 init.cpp:333] osquery initialized [version=4.4.0-19-g336e6b07-dirty]
I0828 18:00:20.466637 26260 init.cpp:340] Using default flagfile: /etc/osquery/osquery.flags
I0828 18:00:20.466708 26260 extensions.cpp:452] Could not autoload extensions: Cannot open file for reading: /etc/osquery/extensions.load
I0828 18:00:20.466806 26260 dispatcher.cpp:77] Adding new service: WatcherRunner (0x56344c6b46e8) to thread: 139911222703872 (0x56344c6b18c0) in process 26260
I0828 18:00:20.468546 26263 watcher.cpp:611] osqueryd watcher (26260) executing worker (26264)
WARNING: Logging before InitGoogleLogging() is written to STDERR
Using a virtual database. Need help, type '.help'
osquery> .quit
I0828 18:00:35.484007 26263 watcher.cpp:611] osqueryd watcher (26260) executing worker (26311)
WARNING: Logging before InitGoogleLogging() is written to STDERR
Using a virtual database. Need help, type '.help'
osquery> 
```
### What did you expect to see?
osqueryi quit after executing `.quit`

### What did you see instead?
osqueryi didn't quit

### PR DESCRIPTION
**Pull request by theopolis**
Fixes #6613.

There should be a test for this but `test_osqueryi` is not working right now. I will try to address this in a follow up.

### CODE REVIEW

File: osquery/core/init.cpp [hunk 1]
```diff
@@ -291,6 +290,13 @@ Initializer::Initializer(int& argc,
   // Let gflags parse the non-help options/flags.
   GFLAGS_NAMESPACE::ParseCommandLineFlags(argc_, argv_, isShell());
 
+  if (isShell()) {
+    // Do not set these values before calling ParseCommandLineFlags.
```
Comment (directionless) [inline osquery/core/init.cpp:294]:
```suggestion
    // Set these values after calling ParseCommandLineFlags.
```

Comment (theopolis) [reply osquery/core/init.cpp:294]: It's a good suggestion but I don't feel like it's really a double negative. I prefer to have the "Do not" as a more powerful hint to anyone making changes.
