### PR TITLE
Restrict access to Thrift server pipe on Windows

### LINKED ISSUE #6798: Windows: establish secure ACLs on the Thrift pipe
# Bug report

It has been brought to my attention (semi-publicly, a couple of times, which is why I'm making a GitHub issue for it here) that the Thrift (named pipe `\Device\NamedPipe\osquery.em`) on Windows is created by osquery in such a way that any user can access it, rather than just Administrator.

### What operating system and version are you using?

Windows (affected versions TBD, probably all)

### What version of osquery are you using?

4.5

### What steps did you take to reproduce the issue?

`osqueryi.exe --disable_extensions=false --extensions_socket="\\.\pipe\osquery.em"`

Then, find the handle using SysInternals Process Explorer's "Find Handles or DLLs" and searching for "osquery.em" or selecting `osqueryd.exe` in the process list and viewing the handles and DLLs pane, then checking the security properties on the handle `Device\NamedPipe\osquery.em`.

Alternatively, use SysInternals `accesschk`:

```
accesschk \pipe\shell.em

Accesschk v6.13 - Reports effective permissions for securable objects
Copyright ⌐ 2006-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

\\.\Pipe\shell.em
  RW Everyone
  RW BUILTIN\Administrators
```

### What did you expect to see?

NamedPipe should not be accessible by unprivileged users.

### What did you see instead?

image

### PR DESCRIPTION
**Pull request by mike-myers-tob**
Closes #6798 

This PR replaces, on Windows, the call to the `TPipeServer` constructor with the recently added (to Thrift, and then patched into our build by @theopolis) constructor that allows the explicit setting of a security descriptor.

Before:

```
accesschk \pipe\shell.em

Accesschk v6.13 - Reports effective permissions for securable objects
Copyright ⌐ 2006-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

\\.\Pipe\shell.em
  RW Everyone
  RW BUILTIN\Administrators
```

With this fix:

```
Accesschk v6.13 - Reports effective permissions for securable objects
Copyright ⌐ 2006-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

\\.\Pipe\shell.em
  Error getting security:
  Access is denied.
No matching objects found.
```

;-)

You have to check it in an Administrator command prompt now:

```
Accesschk v6.13 - Reports effective permissions for securable objects
Copyright ⌐ 2006-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

\\.\Pipe\shell.em
  RW NT AUTHORITY\SYSTEM
  RW BUILTIN\Administrators
```

I've tested with Trail of Bits' extensions and they are able to connect to this and to provide their functionality.

```
PS C:\Projects\osquery\build> .\osquery\RelWithDebInfo\osqueryi.exe --allow_unsafe --disable_extensions=false --extension .\external\extension_trailofbits\RelWithDebInfo\trailofbits_osquery_extensions.ext.exe
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> SELECT * FROM HostDenylist;
+---------+---------------------------+--------------+----------------+-----------+
| address | domain                    | sinkhole     | firewall_block | dns_block |
+---------+---------------------------+--------------+----------------+-----------+
|         | bitbucket.corp.ncrypt.com | 10.130.21.63 |                | UNMANAGED |
+---------+---------------------------+--------------+----------------+-----------+
```

### CODE REVIEW

File: osquery/extensions/impl_thrift.cpp [hunk 1]
```diff
@@ -318,7 +318,16 @@ void ExtensionRunnerInterface::serve() {
 }
 
 void ExtensionRunnerInterface::connect() {
+#ifdef WIN32
+  // Specify a security descriptor string, in SDDL format, that allows access
+  // (to the named pipe) only to the System and the Built-in Administrators.
+  const std::string& securityDescriptor = "D:(A;;FA;;;SY)(A;;FA;;;BA)";
```
Comment (theopolis) [inline osquery/extensions/impl_thrift.cpp:324]: Is it possible to inspect who is running osquery(d|i) and also give them access?

**Review by theopolis — CHANGES_REQUESTED** [review]

File: osquery/extensions/impl_thrift.cpp (hunk 1 above)
Comment (ustas7sea) [reply osquery/extensions/impl_thrift.cpp:324]: would be nice to have this feature (give access to user who started osqueryd/i) for testing. Tests account might not be Admin.

Comment (mike-myers-tob) [reply osquery/extensions/impl_thrift.cpp:324]: Yes, this should be possible, and I'm adding that now.

**Review by theopolis — APPROVED** [review]
