### PR TITLE
magic: Check return from magic_file

### LINKED ISSUE #6356: osqueryi 4.1.2 `magic` table segfault
# Bug report

### What operating system and version are you using?

 version = 10.15.3
   build = 19D76
platform = darwin

### What version of osquery are you using?

version = 4.1.2

### What steps did you take to reproduce the issue?

Specified the magic file `/usr/share/file/magic.mgc` from the `file` command to get correct type identification data
```
select * from magic where path = '/Users/me/Downloads/me.jpg' and magic_db_files='/usr/share/file/magic.mgc';
```

### What did you expect to see?

The correct identification information

### What did you see instead?

Segfault

### Some Context

I wanted to do hashing based on file type, so I started with this
```
osquery> .mode line
osquery> select * from magic where path = '/Users/me/Downloads/file.tar.gz';
          path = /Users/me/Downloads/file.tar.gz
magic_db_files = /usr/share/file/magic/magic
          data = data
     mime_type = application/octet-stream
 mime_encoding = binary
```
That didn't seem correct though. `file.tar.gz` should produce a `mime_type` of `application/gzip`. 

So I figured the `magic_db_files` needed to point to something else - that worked...sort of...
```
osquery> select * from magic where path = '/Users/me/Downloads/file.tar.gz' and magic_db_files='/usr/share/file/magic.mgc';
          path = /Users/me/Downloads/file.tar.gz
magic_db_files = /usr/share/file/magic.mgc
          data = gzip compressed data, was "test_file.tar", last modified: Tue May 30 17:51:27 2017, max compression
     mime_type = application/gzip
 mime_encoding = binary
```

However running the same query but on a different file (a JPEG image), causes a segfault
```
osquery> select * from magic where path = '/Users/me/Downloads/me.jpg' and magic_db_files='/usr/share/file/magic.mgc';
Segmentation fault: 11
```
I tried other `magic.mgc` files, but that didn't make a difference. Trying multiple `jpg` files seems to indicate that a `jpg` with the following magic will cause this issue

```
JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=12, height=3024, manufacturer=Google, model=Pixel 2, orientation=upper-right, xresolution=173, yresolution=181, resolutionunit=2, software=HDR+ 1.0.265696846zp, datetime=2020:02:21 16:00:47, width=4032]
```

An edited version of that same image with the following magic works just fine (perhaps the Exif data is causing an issue?)
```
osquery> select * from magic where path = '/Users/me/Downloads/me_4x4.jpg' and magic_db_files='/usr/share/file/magic.mgc';
          path = /Users/me/Downloads/me_4x4.jpg
magic_db_files = /usr/share/file/magic.mgc
          data = JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=0], progressive, precision 8, 3024x4000, components 3
     mime_type = image/jpeg
 mime_encoding = binary
```

###  Stack  trace
I've only got `lldb` on this system, so I hope this helps at least a little :)

```
Process 50898 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fff708c5c92 libsystem_platform.dylib`_platform_strlen + 18
libsystem_platform.dylib`_platform_strlen:
->  0x7fff708c5c92 <+18>: pcmpeqb (%rdi), %xmm0
    0x7fff708c5c96 <+22>: pmovmskb %xmm0, %esi
    0x7fff708c5c9a <+26>: andq   $0xf, %rcx
    0x7fff708c5c9e <+30>: orq    $-0x1, %rax
Target 0: (osqueryi) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00007fff708c5c92 libsystem_platform.dylib`_platform_strlen + 18
    frame #1: 0x00007fff6d7e3caf libc++.1.dylib`std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*) + 21
    frame #2: 0x00000001003793d4 osqueryi`___lldb_unnamed_symbol17825$$osqueryi + 1241
    frame #3: 0x00000001000ae7eb osqueryi`___lldb_unnamed_symbol4710$$osqueryi + 43
    frame #4: 0x000000010003ceca osqueryi`___lldb_unnamed_symbol1337$$osqueryi + 3748
    frame #5: 0x000000010085f090 osqueryi`___lldb_unnamed_symbol42554$$osqueryi + 8887
    frame #6: 0x0000000100836b98 osqueryi`___lldb_unnamed_symbol41907$$osqueryi + 374
    frame #7: 0x0000000100121d34 osqueryi`___lldb_unnamed_symbol8374$$osqueryi + 263
    frame #8: 0x0000000100123adf osqueryi`___lldb_unnamed_symbol8382$$osqueryi + 447
    frame #9: 0x0000000100122c7b osqueryi`___lldb_unnamed_symbol8377$$osqueryi + 1276
    frame #10: 0x000000010011eff5 osqueryi`___lldb_unnamed_symbol8310$$osqueryi + 252
    frame #11: 0x000000010011f36c osqueryi`___lldb_unnamed_symbol8311$$osqueryi + 806
    frame #12: 0x000000010011f9fa osqueryi`___lldb_unnamed_symbol8321$$osqueryi + 37
    frame #13: 0x00007fff706cf7fd libdyld.dylib`start + 1
```

### PR DESCRIPTION
**Pull request by theopolis**
Fixes #6356.

### CODE REVIEW

File: osquery/tables/system/posix/magic.cpp [hunk 1]
```diff
@@ -19,61 +22,37 @@ namespace tables {
 
 namespace {
 
-constexpr std::array<const char*, 3> kMagicFiles = {{
-    "/usr/share/misc/magic",
```
Comment (directionless) [inline osquery/tables/system/posix/magic.cpp:23]: Is the removal of this intentional?

Comment (theopolis) [reply osquery/tables/system/posix/magic.cpp:23]: Yes, per documentation a folder is only relevant if you plan to use the compile APIs.
