### PR TITLE
Fix and document discovery queries behavior on distributed queries and add tests

### LINKED ISSUE #5260: Distributed queries execute regardless of discovery
# Bug report

According to the documentation, "If all of the discovery queries return more than zero rows, then the queries are added to the query schedule".  However, the code in distributed.cpp acceptWork() will add queries regardless of the discovery scan results.

### What operating system and version are you using?

The bug is cross platform. I'm on MacOS X 10.13.6

### What version of osquery are you using?

version = 3.3.1-32-g28ffde72

### What steps did you take to reproduce the issue?

Use a distributed setup with a discovery query.  For example, the following 1_1 query should never run, since the discovery 'past' query will not return any rows

`{"discovery":{"past":"SELECT * from time where year=1902;"}, "queries":{"1_1":"SELECT * FROM osquery_info;"}}`

### What did you expect to see?

The response from the above request should be:

`{"queries":{"1_1":[]},"statuses":{"1_1":0}}`

### What did you see instead?

The result for queries '1_1' will be populated.

### PR DESCRIPTION
**Pull request by lucasmrod**
This PR fixes and attempts to document the discovery queries behavior in distributed queries.

The main change:
If a distributed query does not have its corresponding discovery query, then it will always be executed.
(Currently on `master` this is not the case, if there's at least one discovery query then all those distributed queries that do not have one defined are not executed at all.)

This PR also fixes #5260 and #7793 and adds some tests to `Distributed.acceptWork`.

### CODE REVIEW

File: osquery/distributed/distributed.cpp [hunk 1]
```diff
@@ -229,7 +233,7 @@ Status Distributed::acceptWork(const std::string& work) {
           return Status(1, "Distributed query is not a string");
         }
 
-        if (queries_to_run.empty() || queries_to_run.count(name)) {
+        if (!hasDiscoveryQueries || queries_to_run.count(name)) {
```
Comment (directionless) [inline osquery/distributed/distributed.cpp:236]: I'm not sure I understand how this fixes the bug described in #5260. How is this behavior different that prior? (I'm not enough of a c person to discern if there's something clever happening)

Are there cases hasDiscoveryQueries is false, but not `!queries_to_run.empty()`?

Comment (lucasmrod) [reply osquery/distributed/distributed.cpp:236]: Hi!, it's a pretty confusing feature/logic.

Currently in `master`:
1. `queries_to_run` starts empty.
2. First `for` loop iterates the received `discovery` queries. For each discovery query, if they return > 0 results, then the query `name` is added to `queries_to_run`. 
3. Second `for` loop iterates the received `queries` and, "stores them in the database to be run in runQueries" if `queries_to_run` is empty or if the corresponding `discovery` query returned > 0 results.

> Are there cases hasDiscoveryQueries is false, but not !queries_to_run.empty()?

The bug in `master` is that if _there are_ discovery queries and _all_ of them return no results, then `queries_to_run` will be empty, and therefore *all* queries are incorrectly enqueued for execution (because it's using `queries_to_run.empty()` in the `if`).

> if (!hasDiscoveryQueries || queries_to_run.count(name)) {

I believe this change fixes the above bug:
- All queries are queued if there are no `discovery` queries (`hasDiscoveryQueries=false`).
- If `hasDiscoveryQueries=true`, then the query is only enqueued if it returned results `queries_to_run.count(name) == true`.

Let me know if it makes sense.

Comment (lucasmrod) [reply osquery/distributed/distributed.cpp:236]: Also, this PR just fixes a corner-case in the current logic, it does not try to change such logic (discussed in https://github.com/osquery/osquery/issues/5260#issuecomment-1171892909).

Comment (lucasmrod) [reply osquery/distributed/distributed.cpp]: I've ended up fixing the "odd behavior" and adding documentation instead. Let me know of (by reading docs and tests) it now makes more sense.

**Review by zwass — APPROVED** [review]
This looks to be well-documented and tested. Thank you @lucasmrod! @directionless any further questions/concerns from you? Otherwise I'll merge later today.
